// <auto-generated />
namespace CollectorsPlace.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Avatar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Avatar));
        
        string IMigrationMetadata.Id
        {
            get { return "201305262136567_Avatar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
