// <auto-generated />
namespace CollectorsPlace.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Mensagens : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mensagens));
        
        string IMigrationMetadata.Id
        {
            get { return "201305282333244_Mensagens"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
